global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: mvc-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["mvc-gateway:8080"]

  - job_name: reactive-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "reactive-gateway:8080" ]

